name: Go Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Run tests
      run: |
        cd tgs-004/go/
        echo "Running tests in $(pwd)"  # This line will print the current directory
        go test -v ./...
